apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-spring-boot-k8s
  template:
    metadata:
      labels:
        app: demo-spring-boot-k8s
    spec:
      containers:
        - name: demo-spring-boot-k8s
          image: rea9r/demo-spring-boot-k8s
          ports:
            - containerPort: 8080
