apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-k8s-service
spec:
  type: NodePort
  selector:
    app: demo-spring-boot-k8s
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
