apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-spring-boot-k8s
  template:
    metadata:
      labels:
        app: demo-spring-boot-k8s
    spec:
      containers:
        - name: demo-spring-boot-k8s
          image: rea9r/demo-spring-boot-k8s
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-k8s-service
spec:
  type: NodePort
  selector:
    app: demo-spring-boot-k8s
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
