apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-spring-boot-k8s-service-monitor
  labels:
    release: prometheus
spec:
  endpoints:
    - port: http-traffic
      path: /actuator/prometheus
      interval: 5s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: demo-spring-boot-k8s
